services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./app/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-fastapi-jupyter-network
  fastapi:
    image: kojamad28/postgres-jupyter-fastapi-prod
    container_name: fastapi
    build: 
      context: ./app
      args:
        REQ_DIR: "requirements/"
        REQ_TXT: "prod.txt"
    command: uvicorn main:app --host=0.0.0.0 --port=8000
    volumes:
      - ./app:/usr/src/app/
    expose:
      - "8000"
    env_file:
      - ./app/postgres/.env
    depends_on:
      - postgres
    networks:
      - postgres-fastapi-jupyter-network
  nginx:
    image: kojamad28/fastapi-nginx
    container_name: nginx
    build: ./nginx
    volumes:
      - ./app/static:/usr/src/app/static
      - ./app/media:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - postgres-fastapi-jupyter-network
  jupyter:
    build:
      context: ./jupyter
      args:
        REQ_DIR: "requirements/"
        REQ_TXT: "prod.txt"
    image: kojamad28/postgres-fastapi-jupyter-prod
    container_name: jupyterlab
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./jupyter:/usr/src/app
    tty: true
    stdin_open: true
    depends_on:
      - nginx
    networks:
      - postgres-fastapi-jupyter-network

networks:
  postgres-fastapi-jupyter-network:
    driver: bridge

volumes:
  postgres_data:
